import { Space_Grotesk } from "next/font/google"; // Import the Space Grotesk font
import "./globals.css";

const spaceGrotesk = Space_Grotesk({ subsets: ["latin"] }); // Use the Space Grotesk font

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={spaceGrotesk.className}>{children}</body>
      {/* Apply the Space Grotesk font */}
    </html>
  );
}
